namespace LightStone4net.WinUI
{
	partial class HrvSdnnPlotControl
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.m_Timer = new System.Windows.Forms.Timer(this.components);
			this.m_PlotSurface = new NPlot.Windows.PlotSurface2D();
			this.SuspendLayout();
			// 
			// m_Timer
			// 
			this.m_Timer.Tick += new System.EventHandler(this.OnTimerTick);
			// 
			// m_PlotSurface
			// 
			this.m_PlotSurface.AutoScaleAutoGeneratedAxes = false;
			this.m_PlotSurface.AutoScaleTitle = false;
			this.m_PlotSurface.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.m_PlotSurface.DateTimeToolTip = false;
			this.m_PlotSurface.Dock = System.Windows.Forms.DockStyle.Fill;
			this.m_PlotSurface.Legend = null;
			this.m_PlotSurface.LegendZOrder = -1;
			this.m_PlotSurface.Location = new System.Drawing.Point(0, 0);
			this.m_PlotSurface.Name = "m_PlotSurface";
			this.m_PlotSurface.RightMenu = null;
			this.m_PlotSurface.ShowCoordinates = true;
			this.m_PlotSurface.Size = new System.Drawing.Size(150, 150);
			this.m_PlotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.m_PlotSurface.TabIndex = 3;
			this.m_PlotSurface.Text = "plotSurface2D";
			this.m_PlotSurface.Title = "";
			this.m_PlotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.m_PlotSurface.XAxis1 = null;
			this.m_PlotSurface.XAxis2 = null;
			this.m_PlotSurface.YAxis1 = null;
			this.m_PlotSurface.YAxis2 = null;
			// 
			// HrvSdnnPlotControl
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.m_PlotSurface);
			this.Name = "HrvSdnnPlotControl";
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.Timer m_Timer;
		private NPlot.Windows.PlotSurface2D m_PlotSurface;
	}
}
