using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("http://www.hessmer.org")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2006 Dr. Rainer Hessmer")]
[assembly: AssemblyTrademarkAttribute("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersionAttribute("0.5.0.0")]
//[assembly: AssemblyFileVersion("0.5.0.0")]


